apiVersion: v1
kind: Pod
spec:
  tolerations:
    - key: nodeType
      operator: Equal
      value: "build-standard-2"
      effect: NoSchedule
  nodeSelector:
    workload: "build"
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
  containers:
    - name: gradle
      image: gradle:7-jdk11
      command:
        - sleep
      args:
        - infinity
      resources:
        requests:
          memory: 4Gi
          cpu: 1000m